#!/usr/bin/env bash
# stop the 4-to_infinity_and_beyond process

# shellcheck disable=SC2009

pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')
[ -n "$pid" ] && kill "$pid"
